// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.bq.vertxgrpcexample.api.proto;

public interface DeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DeleteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   */
  boolean getOk();
}
