// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.bq.vertxgrpcexample.api.proto;

public interface FetchAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FetchAllRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 from = 1;</code>
   */
  int getFrom();

  /**
   * <code>int32 to = 2;</code>
   */
  int getTo();
}
