// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.bq.vertxgrpcexample.service.proto;

public interface FetchPersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FetchPersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
