// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.bq.sdk.api.proto;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FetchPersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FetchPersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FetchAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FetchAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FetchAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FetchAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\005proto\"P\n\006Person\022\n\n\002id\030\001 " +
      "\001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\r\n\005e" +
      "mail\030\004 \001(\t\022\013\n\003age\030\005 \001(\005\" \n\022FetchPersonRe" +
      "quest\022\n\n\002id\030\001 \001(\t\"+\n\017FetchAllRequest\022\014\n\004" +
      "from\030\001 \001(\005\022\n\n\002to\030\002 \001(\005\"1\n\020FetchAllRespon" +
      "se\022\035\n\006people\030\001 \003(\0132\r.proto.Person\"\034\n\016Del" +
      "eteResponse\022\n\n\002ok\030\001 \001(\0102\227\002\n\rPersonServic" +
      "e\022,\n\014CreatePerson\022\r.proto.Person\032\r.proto" +
      ".Person\0227\n\013FetchPerson\022\031.proto.FetchPers" +
      "onRequest\032\r.proto.Person\022;\n\010FetchAll\022\026.p",
      "roto.FetchAllRequest\032\027.proto.FetchAllRes" +
      "ponse\022,\n\014UpdatePerson\022\r.proto.Person\032\r.p" +
      "roto.Person\0224\n\014DeletePerson\022\r.proto.Pers" +
      "on\032\025.proto.DeleteResponseB%\n\024com.bq.sdk." +
      "api.protoB\013PersonProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "LastName", "Email", "Age", });
    internal_static_proto_FetchPersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_FetchPersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FetchPersonRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_proto_FetchAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_FetchAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FetchAllRequest_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_proto_FetchAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_FetchAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FetchAllResponse_descriptor,
        new java.lang.String[] { "People", });
    internal_static_proto_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteResponse_descriptor,
        new java.lang.String[] { "Ok", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
